# Generated by Django 6.1.1 on 2026-09-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('industry', models.CharField(default='Manufacturing', max_length=100)),
                ('sap_product', models.CharField(default='SAP S/4HANA', max_length=100)),
                ('implementation_type', models.CharField(default='Greenfield', max_length=100)),
                ('modules', models.JSONField(default=list)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('health', models.CharField(default='On Track', max_length=50)),
                ('health_score', models.IntegerField(default=80)),
                ('progress', models.IntegerField(default=0)),
                ('knowledge_coverage', models.IntegerField(default=0)),
                ('project_manager', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('open_questions', models.IntegerField(default=0)),
                ('critical_questions', models.IntegerField(default=0)),
                ('team', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
