# Generated by Django 6.1.1 on 2026-09-24 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='critical_questions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='open_questions',
        ),
        migrations.AddField(
            model_name='project',
            name='cumulative_decisions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='cumulative_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='cumulative_risks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='health',
            field=models.CharField(choices=[('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Critical', 'Critical')], default='On Track', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='health_score',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(default='Manufacturing', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='sap_product',
            field=models.CharField(default='SAP S/4HANA (Private / On-Premise)', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='In Progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='project_docs/')),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.CharField(blank=True, default='', max_length=100)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
