# Generated by Django 6.1.1 on 2026-09-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(default='MM', max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(blank=True, default='', max_length=50)),
                ('participants', models.IntegerField(default=1)),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('preparation_score', models.IntegerField(default=0)),
                ('analysis_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
            ],
        ),
    ]
