# Generated by Django 6.1.1 on 2026-09-09 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='industry',
            field=models.CharField(default='Manufacturing', max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='join_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='meeting',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='meetings_media/'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='post_meeting_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='meeting',
            name='pre_meeting_preparation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='teams_meeting_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='SAP Meeting', max_length=255),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='preparation_score',
            field=models.IntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='topic',
            field=models.CharField(default='SAP Requirement Workshop', max_length=255),
        ),
    ]
