# Generated by Django 6.1.1 on 2026-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_options_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='user_email',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
