# Generated by Django 6.1.1 on 2026-09-16 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='meeting_docs/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
