# Generated by Django 6.1.1 on 2026-09-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='erp_system',
            field=models.CharField(blank=True, default='SAP S/4HANA (Private / On-Premise)', max_length=120),
        ),
    ]
