# Generated by Django 6.1.1 on 2026-09-23 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_erp_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='erp_system',
            field=models.CharField(blank=True, default='SAP S/4HANA (Private / On-Premise)', max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='industry',
            field=models.CharField(default='Manufacturing', max_length=150),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='join_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='module',
            field=models.CharField(default='MM', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='SAP Meeting', max_length=500),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='topic',
            field=models.CharField(default='SAP Requirement Workshop', max_length=500),
        ),
        migrations.AlterField(
            model_name='meetingdocument',
            name='file_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingdocument',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingdocument',
            name='filename',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='meetingdocument',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=500, primary_key=True, serialize=False),
        ),
    ]
