# Generated by Django 6.1.1 on 2026-09-24 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_date_alter_meeting_erp_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin (Executive Control)'), ('Team Leader', 'Team Leader'), ('Project Manager', 'Project Manager'), ('Consultant', 'Consultant')], default='Consultant', max_length=100),
        ),
    ]
